apiVersion: v1
kind: Namespace
metadata:
  name: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: registry.cn-hangzhou.aliyuncs.com/test-devops1/devops:2.0
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: application
spec:
  selector:
    app: myapp  # 这里应与 Deployment 中定义的标签匹配
  ports:
    - protocol: TCP
      port: 8084  # Service 监听的端口
      targetPort: 8084  # Pod 中容器实际监听的端口
      nodePort: 30084
  type: NodePort # Service 类型，默认ClusterIP，也可以是NodePort, LoadBalancer等