name: "bluebell"
mode: "debug"
port: 8084
version: "v0.0.1"
start_time: "2020-07-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "10.0.0.100"
  port: 30001
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "10.0.0.100"
  port: 30002
  password: "123456"
  db: 0
  pool_size: 100
